### ISSUE TITLE
Reduce the major and minor graduation 

### ISSUE THREAD

**Issue by arunrajiah** [stherrienaspnet/ngRadialGauge#18]
I am using the below code,

$scope.majorGraduations = 10;
$scope.minorGraduations = 0;

Am I doing anything wrong here?

**Comment by haroon786** [comment]
i draw 3 gauge but h how to reduce gape of them 
![1](https://cloud.githubusercontent.com/assets/20164301/16374933/6ec55860-3c76-11e6-82ca-16c4f2b6b871.png)

plzzz help me and also how to customize the Background gnerated svg code

**Comment by stherrienaspnet** [comment]
Send me a plunker link and I will make modification to it.
On Jun 27, 2016 5:20 AM, "haroon786" notifications@github.com wrote:

i draw 3 gauge but h how to reduce gape of them
[image: 1]
https://cloud.githubusercontent.com/assets/20164301/16374933/6ec55860-3c76-11e6-82ca-16c4f2b6b871.png

plzzz help me and also how to customize the Background gnerated svg code

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/stherrienaspnet/ngRadialGauge/issues/18#issuecomment-228694726,
or mute the thread
https://github.com/notifications/unsubscribe/AF19cYeH18WgiWXV-TyNOflY_qCb-2-Vks5qP5X3gaJpZM4IpE5R
.

**Comment by haroon786** [comment]
http://embed.plnkr.co/sP0dHuGoCpaIvCiqoNxF/

**Comment by haroon786** [comment]
http://embed.plnkr.co/sP0dHuGoCpaIvCiqoNxF/

**Comment by haroon786** [comment]
http://embed.plnkr.co/sP0dHuGoCpaIvCiqoNxF/
